### ISSUE TITLE
Closing and removing reference to socket doesn't clean up registry?

### ISSUE THREAD

**Issue by marceau-maubert** [FredyH/GWSockets#21] opened 2020-06-24 19:31 UTC
I've noticed that when closing a socket and removing the reference to it, if I look through the registry it'll stay there, even after trying to collect garbage. Is this intended?

[Also here's a random typo](https://github.com/FredyH/GWSockets/blob/4ef5ea5970ac715d224387916159b9d0e9a48ee8/src/GWSocket.h#L55)

**Comment by FredyH** [comment] 2020-06-24 19:50
I fixed the typo.
[This code](https://github.com/FredyH/GWSockets/blob/4ef5ea5970ac715d224387916159b9d0e9a48ee8/src/GLua.cpp#L334) should be responsible for freeing the reference to the socket after it has been closed. I don't believe I hold a reference to it anywhere else, so at some point it should be gced.

**Comment by notcake** [comment] 2020-06-24 20:05
We are seeing that the registry slot allocated by `ReferenceCreate` is never cleared, so `ReferenceFree` must not be getting run after calling `:close()`.

**Comment by marceau-maubert** [comment] 2020-06-24 20:08
https://github.com/Metastruct/gmod-metaconcord/commit/1e92d74a0a57b88b13857c30d2e92f724beeda54

The change introduced in this commit apparently fixes my problem with user data sticking in the registry, somehow? Is this how?

**Comment by FredyH** [comment] 2020-06-24 20:10
Not gonna lie, you really didn't make it easy for me to spot the difference by converting all the indentation to tabs. Do you have any idea which line caused it?

**Comment by marceau-maubert** [comment] 2020-06-24 20:11
I'm sorry, it wasn't intended.

Basically, I made the socket nil itself on disconnect and that makes it clean itself from the registry, in theory.

**Comment by FredyH** [comment] 2020-06-24 20:12
I don't see how setting self to nil would actually change anything, since self is just a parameter of the function.

**Comment by FredyH** [comment] 2020-06-24 20:29
I have actually found a bug where it would leak references. If you close a socket and then reopen it immediately (i.e. from the onDisconnected() callback), it will create a new reference and overwrite the old one in the socketTableReferences.

Was that possibly the cause in your case? If so I will quickly test and then push my changes.

**Comment by marceau-maubert** [comment] 2020-06-24 23:13
I personally wasn't able to reproduce anymore, I don't know if you've tested with cake. Maybe it was something to do with the server itself

**Comment by FredyH** [comment] 2020-06-24 23:16
Alright, in that case I will close this for now. If it happens again feel free to reopen the issue.

**Closed by FredyH** 2020-06-24 23:16 UTC
